# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('review', models.IntegerField(blank=True, choices=[(0, 'good'), (1, 'Average'), (2, 'Bad')], null=True)),
                ('rating', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
